### ISSUE TITLE
Gst-plugins-base-1.0 is looking for the wrong system library

### ISSUE THREAD

**Issue by Nickiel12** [ianprime0509/zig-gobject#82]
I am trying to use the v0.2.2 release with the gnome47 bindings, but there is an issue with the gstreamer plugin bindings. In the distributed `build.zig` there is this line:
```ts
    const gstbase1 = b.addModule("gstbase1", .{
        .root_source_file = b.path(b.pathJoin(&.{ "src", "gstbase1", "gstbase1" ++ ".zig" })),
        .target = target,
        .optimize = optimize,
    });
    gstbase1.link_libc = true;
    gstbase1.linkSystemLibrary("gstreamer-base-1.0", .{});
```
However, the `linkSystemLibrary` should be looking for `gstbase-1.0` because gstreamer has different names for it's packages and distributed binary names. The same issue is present in the `gstreamer-app-1.0` library which should link to `gstapp-1.0`. 

For an example, see the zig output below:
```sh
error: error: unable to find dynamic system library 'gstreamer-app-1.0' using strategy 'paths_first'. searched paths:
  /nix/store/hjw2vq8z7vc9f5q8w9ni3jay1ixppfh5-zig-0.14.0-dev.1831+ce5a5c361/lib/libgstreamer-app-1.0.so
  /nix/store/hjw2vq8z7vc9f5q8w9ni3jay1ixppfh5-zig-0.14.0-dev.1831+ce5a5c361/lib/libgstreamer-app-1.0.a
   -- snip --
  /nix/store/092sh0nakgk3pfqm04h9b8amc3s57gdv-gst-plugins-base-1.24.3/lib/libgstreamer-app-1.0.so
  /nix/store/092sh0nakgk3pfqm04h9b8amc3s57gdv-gst-plugins-base-1.24.3/lib/libgstreamer-app-1.0.a
```
but when you ls the gst-plugins-base folder it is looking in:
```sh
╰─❯ ls /nix/store/092sh0nakgk3pfqm04h9b8amc3s57gdv-gst-plugins-base-1.24.3/lib/                                                                               1 ✘  impure   03:02:08   girepository-1.0/                  libgstaudio-1.0.so@                libgstgl-1.0.so.0.2403.0*          libgstrtp-1.0.so.0@                libgsttag-1.0.so@
gstreamer-1.0/                     libgstaudio-1.0.so.0@              libgstpbutils-1.0.so@              libgstrtp-1.0.so.0.2403.0*         libgsttag-1.0.so.0@
libgstallocators-1.0.so@           libgstaudio-1.0.so.0.2403.0*       libgstpbutils-1.0.so.0@            libgstrtsp-1.0.so@                 libgsttag-1.0.so.0.2403.0*
libgstallocators-1.0.so.0@         libgstfft-1.0.so@                  libgstpbutils-1.0.so.0.2403.0*     libgstrtsp-1.0.so.0@               libgstvideo-1.0.so@
libgstallocators-1.0.so.0.2403.0*  libgstfft-1.0.so.0@                libgstriff-1.0.so@                 libgstrtsp-1.0.so.0.2403.0*        libgstvideo-1.0.so.0@
libgstapp-1.0.so@                  libgstfft-1.0.so.0.2403.0*         libgstriff-1.0.so.0@               libgstsdp-1.0.so@                  libgstvideo-1.0.so.0.2403.0*
libgstapp-1.0.so.0@                libgstgl-1.0.so@                   libgstriff-1.0.so.0.2403.0*        libgstsdp-1.0.so.0@
libgstapp-1.0.so.0.2403.0*         libgstgl-1.0.so.0@                 libgstrtp-1.0.so@                  libgstsdp-1.0.so.0.2403.0*
```
And as you can see, there does exist a `libgstapp-1.0.so` file.

**Comment by Nickiel12** [comment]
If you would like, I would be happy to work on a fix for this if you could point me to the right section of the codebase.

**Comment by ianprime0509** [comment]
The libraries which are linked for each module come from the `package` elements in the GIR files: https://github.com/ianprime0509/zig-gobject/blob/875e1fb8fd27df0dc031db60f8055172c465acf9/src/translate.zig#L2853-L2855

In this case, referencing the GIR files in the GNOME 47 SDK, the library linked for GstBase-1.0 is
```xml
<package name="gstreamer-base-1.0"/>
```
and for GstApp-1.0, it's
```xml
<package name="gstreamer-app-1.0"/>
```

You're right that the library files themselves don't have these names, but in this case the library name is expected to be passed to pkg-config to obtain the libraries to link and any other necessary C compiler flags. These commands are run within the GNOME 47 SDK Flatpak environment:

```
[📦 org.gnome.Sdk zig-gobject]$ pkg-config --libs gstreamer-base-1.0
-lgstbase-1.0 -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0
[📦 org.gnome.Sdk zig-gobject]$ pkg-config --cflags gstreamer-base-1.0
-I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sysprof-6 -pthread
[📦 org.gnome.Sdk zig-gobject]$ pkg-config --libs gstreamer-app-1.0
-lgstapp-1.0 -lgstbase-1.0 -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0
[📦 org.gnome.Sdk zig-gobject]$ pkg-config --cflags gstreamer-app-1.0
-I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sysprof-6 -pthread
```

Zig's build system (`linkSystemLibrary`) will also invoke pkg-config, if available, to find the same information. This raises a good point, though, which is that if all the `package` elements in GIR refer to pkg-config names, then the `use_pkg_config` option should be set to [`.force`](https://ziglang.org/documentation/master/std/#std.Build.Module.SystemLib.UsePkgConfig) to prevent confusing errors when pkg-config or its required repository files are not available.

If you do have pkg-config installed, I'd also be interested if somehow those packages are available under different pkg-config package names on your system, since that would introduce an unfortunate extra layer of system dependency which this project would need to work around.

**Comment by Nickiel12** [comment]
I am developing on Nix, so I did not have `pkg-config` installed. After adding `pkg-config` it was able to find the libraries required and it got past the library discovery step (and back to my own errors).

If you want any system information from my setup, just let me know! Feel free to close this issue when you want.

**Comment by ianprime0509** [comment]
Awesome, thanks for confirming! In that case, I'll leave this as an enhancement to add `.use_pkg_config = .force` to all the `linkSystemLibrary` calls (once I determine that will be correct in all cases), which should make things a bit less confusing to any future users who might not have installed pkg-config.
